### ISSUE TITLE
suggestion(bbc): Improve match result screen design

### ISSUE THREAD

**Issue by developomp** [War-Brokers/War-Brokers#19]
## Tasks
- [ ] Add breathing animation to player models
- [ ] level up animation
- [ ] XP gain animation
  - XP reward breakdown
- [ ] win / lose animation
- [ ] overall player stats table
  - damage, kills, deaths, etc.

**Comment by developomp** [comment]
bbc is discontinued.
